version: "3.4"

services:
  php:
    image: wordpress:fpm-alpine
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_DB_NAME: $DB_NAME
    networks:
      - internal
    restart: unless-stopped
    volumes:
      - ./scripts/wp-permissions-fix.sh:/tmp/wp-permissions-fix.sh

  nginx:
    image: nginx:alpine
    depends_on:
      - php
    networks:
      - internal
    restart: unless-stopped
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - internal
    restart: unless-stopped
    volumes:
      - ./backup:/docker-entrypoint-initdb.d:ro

networks:
  internal:
    external: false
